version: '3.5'
services:
  post_test:
    image: postgres
    container_name: postgres_test
    environment:
      - POSTGRES_USER: ${POSTGRES_USER:-postgres_supernova_user}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-supernova_pass}
      - PGDATA: /data/postgres
    volumes:
      - $PWD/scriptSQL:/var/lib/postgresql/data
    ports:
      - "5432:5432"
